export class ErrorConstants {
    public static readonly INTERNAL_ERR: string =  "INTERNAL_ERROR";
    public static readonly INVALID_INVITATION_CODE_FORMAT_ERR: string =  "Invalid Code pattern, the characters from '#' must be '#'";
    public static readonly INVALID_JSON_ERR: string =  "INVALID_JSON_ERROR";
    public static readonly INVALID_RESOURCE_URL: string =  "INVALID_RESOURCE_URL";
    public static readonly RESOURCE_NOT_FOUND: string = "RESOURCE_NOT_FOUND";
    public static readonly METHOD_NOT_ALLOWED: string = "METHOD_NOT_ALLOWED";
    public static readonly SHOULD_CONTAINS_ONE_OF_DATA_OR_ERROR: string = "An ApiResponse instance should only contain one of data or error";
    public static readonly INVALID_USER_ACCESS: string = "Please Provide Correct Information";
    public static readonly INVALID_TOKEN: string = "Invalid Token";
    public static readonly SESSION_EXPIRED: string = "Your session is expired. Please login again";
    public static readonly USER_ALREADY_EXIST: object = {message: "User Already Exists!", code: 412};
    public static readonly CHECKPOINT_ALREADY_EXIST: string = "Checkpoint already exist with this ID";
    public static readonly USER_NOT_EXIST: object = {message: "User Does not Exist!", code: 404};
    public static readonly INVALID_HACKED_STARPOINTS: object = {message: "The given hacked star points is greater than maximum available total star points", code: 404};
    public static readonly RACE_CHECKPOINTS_NOT_FOUND: object = {message: "No race checkpoint was found with this ID", code: 404};
    public static readonly RACE_NOT_FOUND: object = {message: "No race found with this ID", code: 404};
    public static readonly RACE_NAME_EDIT_NOT_AVAILABLE: object = {message: "The race name is not available, this race name had been used", code: 404};
    public static readonly RACE_NAME_NULL_OR_EMPTY: object = {message: "The race name can not be null or empty", code: 404};
    public static readonly NO_CHECKPOINT_FOUND: object = {message: "No race checkpoint found with this ID", code: 404};
    public static readonly PARAMATER_NOT_CORRECT: object = {message: "Please Provide Valid Parameters For Save!", code: 400};
    public static readonly INCORRECT_STATUS_SEND: object = {message: "Please Send Correct Race Status!", code: 400};
    public static readonly START_USER_RACE: object = {message: "Please Start The Race First!", code: 412};
    public static readonly NO_RECORD: object = {message: "No record found", code: 404};
    public static readonly NO_LEADERBOARD_RECORD: string = "No leaderboard record found for practice race ID";
    public static readonly NO_CHECKPOINT: string = "No checkpoint record found";
    public static readonly USER_ALREADY_PARTICIPATED_FOR_THE_CHALLENGE: string = "The user already participated for the current race challenge";
    public static readonly USER_ALREADY_PARTICIPATED: object = {message: "The user already participated for the current race", code: 412};
    public static readonly PRACTICE_RACE: object = {message: "No booking need for practice race", code: 412};
    public static readonly USER_ALREADY_REGISTERED_FOR_THE_RACE: object = {message: "User already registered for the race.", code: 412};
    public static readonly BOOKING_NOT_FOUND: object = {message: "No booking record was found", code: 404};
    public static readonly RACE_EVENT_REACHED_MAX_LIMIT: object = {message: "Race event for the current ID is already reached maximum limit", code: 412};
    public static readonly RACE_ALREADY_REACHED_MAX_LIMIT: object = {message: "Race for the current ID already reached maximum limit", code: 412};
    public static readonly RACE_TEAM_MAX_LIMIT: object = {message: "Race team member count should not be greater than maximum limit 6", code: 412}
    public static readonly RACE_TEAM_MIN_LIMIT: object = {message: "Race team member count should not be lesser than minimum limit 2", code: 412}
    public static readonly RACE_EVENT_NOT_MATCH: object = {message: "Race Event not belong to that Race.", code: 412};
    public static readonly NO_PARTICIPANTS: object = {message: "No participants found with the ID", code: 404}
    public static readonly WRONG_CODE: object = {message: "No coupon code was found", code: 404};
    public static readonly WRONG_INVITATION_CODE: object = {message: "Invalid invitation code", code: 404};
    public static readonly USED_CODE: object = {message: "This invitation code is already used", code: 412};
    public static readonly USER_USED_CODE: object = {message: "You have already used this code and joined a team successfully", code: 412};
    public static readonly RACE_ALREADY_EXIST: string = "User already registered for the race";
    public static readonly NO_USER_RECORD_EXIST: object = {message: "No record found with the participant", code: 404};
    public static readonly TEAM_ALREADY_EXIST: object = {message: "Team is already registered with the same name for the same race", code: 412};
    public static readonly IN_VALID_CREDENTIALS: object = {message: "Invalid combination of email and password", code: 401};
    public static readonly WRONG_PASS: object = {message: "Your password does not match", code: 401};
    public static readonly PASS_REQUIRED: object = {message: "Field password is required", code: 400};
    public static readonly NOT_ADMIN: object = {message: "Sorry! Only Admin Can Access it", code: 401} ;
    public static readonly EMAIL_NOT_FOUND: object = {message: "No user was found with that email", code: 404};
    public static readonly USER_NOT_FOUND: object = {message: "No user was found with that ID", code: 404};
    public static readonly RACE_STATS_NOT_FOUND: object = {message: "No user race stats found", code: 404};
    public static readonly USER_HAS_NOT_STARTED_RACE: object = {message: "User has not started race", code: 404};
    public static readonly RACE_EVENT_NOT_STARTED: string = "Race event has not been started ";
    public static readonly RACE_EVENT_NOT_FOUND: object = {message: "No race was found with that event ID", code: 404};
    public static readonly WRONG_USER_ID: string = "Please provide correct user information";
    public static readonly WRONG_RACE_ID: string = "Please provide correct race information";
    public static readonly IN_VALID_GENDER: string = "Invalid Gender";
    public static readonly NO_ROLES: string = "No Roles is database";
    public static readonly DISCOUNT_CODE_EXPIRED: object = {message: "Discount code is expired", code: 401};
    public static readonly DISCOUNT_NOT_FOUND: object = {message: "Discount not found", code: 401};
    public static readonly IN_VALID_OTP: object = {message: "Otp is invalid", code: 401};
    public static readonly USER_NOT_VERIFIED: object = {message: "User Not Verified", code: 401};
    public static readonly NO_CHALLNEGE_RECORD: object = {message: "No challenge record found", code: 404};
    public static readonly USER_ALREADY_VERIFIED: string = "User Already Verified";
    public static readonly INVALID_PARTICIPANT_TYPE: object = {message: "Please Provide Correct Participant Type", code: 400};
    public static readonly INVALID_CODE: object = {message: "Please Provide Correct Code", code: 400};
    public static readonly INVALID_CODE_USED: object = {message: "Please Provide Correct Code - This code used by another race", code: 400};
    public static readonly CODE_USED: object = {message: "This Code has been used by another user", code: 400};
    public static readonly CODE_USER_USED_ANOTHER_CODE_RACE: object = {message: "This User already used another Code for this Race", code: 400};
    public static readonly NO_TEAM: object = {message: "User does not belong to any team", code: 404};
    public static readonly NO_STARPOINT_UPDATE: string = "Starpoint already updated for the current status";
    public static readonly INVALID_STARPOINT: object = {message: "The starpoint can't exceed it's maximum value", code: 400};
    public static readonly NO_STARPOINT_UPDATE_FOR_EXISTING_RECORD: object = {message: "Starpoint already updated for the current status", code: 412};
    public static readonly NO_RECORD_UPDATE_FOR_COMPLETE_FAIL_QUIT: object = {message: "Record can't update for complete, quit or failed status", code: 412};
    public static readonly NO_UPDATE: string = "You are not authorized to update the race. Only admin can access it." ;
    public static readonly NO_NEW_RACE: string = "You are not authorized to create a new race. Only admin can access it." ;
    public static readonly RACE_EXIST: object = {message: "Race Already Exists with the same name", code: 412};
    public static readonly NO_OTP: object = {message: "You must validate the OTP which was sent you", code: 401};
    public static readonly INVALID_CHALLENGE_TYPE: string = "Please enter the valid challenge type";
    public static readonly NO_RECORD_UPDATE_FOR_COMPLETE: object = {message: "Record already updated for complete status", code: 412};
    public static readonly NO_RECORD_UPDATE_FOR_QUIT: object = {message: "Record can't update for race quit", code: 412};
    public static readonly PREMIUM_RACE_NOT_DELETED: string = "Sorry!! Record can't delete. Some Users already signup for that race.";
    public static readonly PRACTICE_RACE_NOT_DELETED: string = "Sorry!! Record can't delete. Some Users are practicing with that race.";
    public static readonly NO_USER_ROLE: object = {message: "No role defined for this user", code: 404};
    public static readonly NOT_SUPER_ADMIN: object = {message: "Sorry! Only Super Admin Can Access it", code: 401} ;
    public static readonly NO_RACE_DELETE_FOR_EXISTING_PARTICIPANTS: object = {message: "Sorry!! Race record can't be deleted for existing participants.", code: 412}
    public static readonly ADMIN_NOT_FOUND: object = {message: "No admin record found with this ID", code: 404};
    public static readonly WRONG_ADMIN_ID: object = {message: "Please provide correct admin information", code: 401};
    public static readonly ADMIN_NOT_DELETED: object = {message: "Admin has created race can't be deleted", code: 412};
    public static readonly NO_RACE_HISTORY: object = {message: "No race history found", code: 404};
    public static readonly NO_EVENT_DELETE_FOR_EXISTING_PARTICIPANTS: object = {message: "Sorry!! Event record can't be deleted for existing participants.", code: 412}
    public static readonly INCORRECT_POINT_TYPE: object = {message: "Please enter correct point type.", code: 400}
    public static readonly USER_NOT_STARTED_RACE: object = {message: "User not started the race.", code: 412}
    public static readonly NO_TERM_RECORD: string = "No record found for the requested term id."
    public static readonly NO_POLICY_RECORD: string = "No record found for the requested policy id."
    public static readonly STATUS_NOT_FOUND: object = {message: "Race Status not found.", code: 404}
    public static readonly RACE_NOT_CREATED: object = {message: "Something went wrong. An insert request for a new race was not excuted successfully", code: 404};
    public static readonly CHECKPOINT_NOT_CREATED: object = {message: "Something went wrong. An insert request for a new checkpoint was not excuted successfully", code: 404};
    public static readonly PHYSICAL_CHALLENGE_NOT_CREATED: object = {message: "Something went wrong. An insert request for a new physical challenge was not excuted successfully", code: 404};
    public static readonly QUIZ_CHALLENGE_NOT_CREATED: object = {message: "Something went wrong. An insert request for a new quiz challenge was not excuted successfully", code: 404};
    public static readonly SPECIAL_CHALLENGE_NOT_CREATED: object = {message: "Something went wrong. An insert request for a new special challenge was not excuted successfully", code: 404};
    public static readonly BOOKING_NOT_CREATED: object = {message: "Something went wrong. The booking request was not excuted successfully", code: 404};
    public static readonly TEAM_NOT_CREATED: object = {message: "Something went wrong. An insert request for a team details was not excuted successfully", code: 404};
    public static readonly CHECKPOINT_IN_LIVE: object = {message: "Can't delete. The checkpoint is on live", code: 404};
    public static readonly CHALLENGE_IN_LIVE: object = {message: "Can't delete. The challenge is on live", code: 404};
    public static readonly CHECK_PARTICIPANTS: object = {message: "Participants min must not be greater than max", code: 404};
    public static readonly CHECK_PRICE: object = {message: "Price is required", code: 404};
    public static readonly CHECK_CODE: object = {message: "Code is required", code: 404};
    public static readonly CHECK_AMOUNT: object = {message: "Amount is required", code: 404};
    public static readonly CHECK_TYPE: object = {message: "Type is required", code: 404};
    public static readonly TEAM_MEMBER_PARTICIPANTS: object = {message: "Team member min must not be greater than max", code: 404};
    public static readonly EXPECTING_INT_VALUE_FOR_RADIUS: object = {message: "Expecting int value for radius", code: 404};

    public static readonly EMPLOYEE_NOT_FOUND: object = {message: "Employee does not existed", code: 400};
    public static readonly EMPLOYEE_UPDATE_FAILED: object = {message: "Employee update failed", code: 400};
    public static readonly SURVEY_UPDATE_FAILED: object = {message: "Survey update failed", code: 400};
    public static readonly EMPLOYEE_WRONG_PASS: object = {message: "Your password is incorrect", code: 401};
    public static readonly UNAUTHORIZED: object = {message: "You are not authorized", code: 404};
    public static readonly NOTAUTHORIZED: object = {message: "You are not authorized for do this action", code: 404};
};
